### PR TITLE
chore: cut a new release

### PR DESCRIPTION
**Pull request by ocavue**

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by egoist** [comment]
oops i should not release it from PR, the branches would not be in sync

CleanShot 2024-09-17 at 11 51 53@2x

**Comment by egoist** [comment]
maybe we should move to a better release tool like changesets in the future

**Comment by sxzz** [comment]
@egoist Do you think bumpp + changelogithub is okay?
https://github.com/sxzz/ts-lib-starter/blob/main/.github/workflows/release.yml

**Comment by egoist** [comment]
> @egoist Do you think bumpp + changelogithub is okay? [sxzz/ts-lib-starter@`main`/.github/workflows/release.yml](https://github.com/sxzz/ts-lib-starter/blob/main/.github/workflows/release.yml?rgh-link-date=2024-09-17T04%3A13%3A12Z)

yeah that's nice, only thing that's missing is commenting on revelant PRs and issues, but i can live without it 👍

CleanShot 2024-09-17 at 12 26 09@2x

**Comment by sxzz** [comment]
@egoist We need to switch default branch to `main`

**Comment by egoist** [comment]
@sxzz feel free to send a PR to add bumpp + changelogithub to main and change the default branch, if you can't change default branch i'll do that later

**Comment by sxzz** [comment]
I've push the commit to main branch without PR, but I have no permission to change the default branch.

**Comment by egoist** [comment]
> I've push the commit to main branch without PR, but I have no permission to change the default branch.

done

**Comment by ocavue** [comment]
Just FYI, deleting `dev` branch closed all pending pull requests in this repo. It might not be a big deal since most of them haven't been approved for quite a while.

**Comment by sxzz** [comment]
Oh my bad...

**Comment by sxzz** [comment]
@egoist Do you agree to add Renovate and [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new#setup) to this repo? These apps require installation on the GitHub repository.

**Comment by egoist** [comment]
LGTM

**Comment by sxzz** [comment]
Installation links: 
- https://github.com/apps/pkg-pr-new
- https://github.com/apps/renovate

**Comment by egoist** [comment]
Installed ✅

**Pull request merged**
