### PR TITLE
Feature/postcss options

### PR DESCRIPTION
**Pull request by malcolm-kee**

### CODE REVIEW

**Comment by egoist** [comment]
why not just use `postcss.config.js`?

**Comment by malcolm-kee** [comment]
@egoist because I'm using `tsup` as a dependency of a custom toolchain, and I want to provide default postcss options when that file is not available.

**Comment by malcolm-kee** [comment]
However if you doesn't want to increase the API surface area, it's fine. I'll maintain my own fork.

**Comment by egoist** [comment]
Sorry, I won't merge this as I want third-party tools' configurations to remain in their own config files.

**Pull request closed without merging**
