### PR TITLE
fix(dts): terminate worker when work is done

### PR DESCRIPTION
**Pull request by SunsetTechuila**
related https://github.com/oven-sh/bun/issues/11760

nothing changes for node, but now tsup can be run on bun: `bun --bun tsup`

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
differs from #1140 in that the worker does not control its own lifecycle

**Comment by SunsetTechuila** [comment]
@egoist hello, would appreciate a review from you

**Comment by SunsetTechuila** [comment]
@sxzz or maybe you can take a look, please?

**Comment by sxzz** [comment]
I'm not very familiar with this part of the code, so I can't review it.

Since Bun already has a issue, we can wait for them to fix compatibility.

**Comment by SunsetTechuila** [comment]
> I'm not very familiar with this part of the code, so I can't review it.

Behavior doesn't change, added code just manually doing what happens automatically 

> Since Bun already has a issue, we can wait for them to fix compatibility.

This can take forever

**Review by sxzz — APPROVED** [review]

**Comment by SunsetTechuila** [comment]
Ty

**Pull request merged**
