### PR TITLE
refactor: replace `globby` with faster alternative

### PR DESCRIPTION
**Pull request by SuperchupuDev**
`globby` has a count of [23](https://npmgraph.js.org/?q=globby) subdependencies, which is far from ideal for something as simple as globbing. This PR switches to a lighter and faster alternative using [`fdir`](https://www.npmjs.com/package/fdir) and [`picomatch`](https://www.npmjs.com/package/picomatch). They have both a total of zero (0) subdependencies, making this not just a faster approach, but also one that's *way* lighter.

This makes tsup go from [102](https://npmgraph.js.org/?q=tsup@8.1.2) subdependencies down to just [88](https://npmgraph.js.org/?q=https%3A%2F%2Fraw.githubusercontent.com%2Fegoist%2Ftsup%2F57a372bb2fa69d75810a699053a2461a024c5a6c%2Fpackage.json).

Note: The patterns at https://github.com/egoist/tsup/blob/57a372bb2fa69d75810a699053a2461a024c5a6c/src/utils.ts#L69-L77 are filtered this way to [properly match](https://github.com/mrmlnc/fast-glob/blob/4df40bd53cc3f71e075d97d013ab4945ca386985/src/utils/pattern.ts#L86-L88) what `globby` (or more specifically, `fast-glob` which is used by `globby`) does. It has some behavior around negated patterns no other globbing library has.

Relevant prior work: dotenvx/dotenvx#278

### CODE REVIEW

**Comment by sxzz** [comment]
I think we can use fdir and picomatch to create a new library for lightweight globbing, enhancing maintainability.

**Comment by SuperchupuDev** [comment]
the implementation here isnt big really, there's a pr in fdir to add a glob function method though (requiring a matcher function) that maybe could be used in the future. i dont really see a need of making it a lib if sometimes picomatch (therefore globbing) isnt even needed

**Review by sxzz — APPROVED** [review]

**Comment by lenovouser** [comment]
I am getting this now after upgrading to `8.2.1`

Screenshot 2024-07-21 at 11 47 51

**Comment by SuperchupuDev** [comment]
i am aware, when conflicts were solved, it looks like picomatch was updated to v4 which fdir's package.json doesn't allow. to fix this tsup must downgrade to picomatch v3 or fdir must release a new version which contains a fix i submitted a few days ago

**Pull request merged**
